#!/bin/sh

function build() {
    containerName="THE_HUB_CONTAINER"
    if [ "$(docker ps -a | grep $containerName)" ]; then
        echo "A container called $containerName is already running"
        echo "Removing container..."
        docker rm -f $containerName
    fi
    echo "Starting production container..."
    docker build -t thehub . && docker run --name $containerName -p 3000:3000 -d thehub
    echo "Started container with name $containerName"
    echo "The application is running at http://localhost:3000"
}

function showHelp() {
    echo "This script builds and runs the front end for the hub."
    echo " "
    echo "options:"
    echo "-b, --build               build and dockerise the production version of the application"
    exit 0
}

for var in "$@"
do
    case "$var" in
    -h | --help)
        showHelp
        break
        ;;
    -b | --build)
        build
        break
        ;;
    esac
done
