name: Run tests and linters on each PR

on: [pull_request]

jobs:
  testAndLint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
    - run: npm ci
    - name: Run test and lint
    - run: npm testAndLint

